/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CRUD;

import java.io.IOException;
import java.util.Scanner;

public class App {
    

    public static void main(String[] args) throws IOException {
        Scanner terminalInput = new Scanner(System.in);
        String pilihanUser;
        boolean isLanjutkan = true;

        while (isLanjutkan) {
        clearScreen();    
            System.out.println("Database Perpustakaan");
            System.out.println("1.\tLihat Selurh Buku");
            System.out.println("2.\tCari Data Buku");
            System.out.println("3.\tTambah Data buku");
            System.out.println("4.\tUbah Data Buku");
            System.out.println("5.\tHapus Data Buku");

            System.out.println("\n\nPilihan Anda :");
            pilihanUser = terminalInput.next();

            switch (pilihanUser) {
                    case "1":
                        System.out.println("LIHAT Seluruh Data Buku");
                        tampilkanData();
                        break;
                    case "2":
                    System.out.println("Cari Buku");
                        break;
                    case "3":
                    System.out.println("Tambah Data Buku");                
                        break;
                    case "4":
                    System.out.println("Ubah Data Buku");                
                        break;
                    case "5":
                    System.out.println("Hapus Data buku");                
                        break;
                
                    default:
                    System.err.println("Input yang anda masukkan tidak ditemukan \n silahkan masukkan angka dari (1-5)");
                        break;
                }

                isLanjutkan = getYesorNo("Apakah Anda ingin melanjutkan");
                }
            }
    private static void tampilkanData() throws IOException {
            System.out.println("Silahkan Tambah Data Anda");
            boolean isTambah = getYesorNo("Apakah Anda ingin Menambah Data lagi ?");

        }
    private static boolean getYesorNo(String message){
        Scanner terminalInput = new Scanner(System.in);
        
        System.out.println("\n"+message+"(y/n)? ");
        String pilihanUser = terminalInput.next();

        while (!pilihanUser.equalsIgnoreCase("y") && !pilihanUser.equalsIgnoreCase("n")) {
            System.err.println("Pilihan Anda bukan Y/N");
            System.out.println("\n"+message+"(y/n)? ");
            pilihanUser = terminalInput.next();
                
        }

        return pilihanUser.equalsIgnoreCase("y");
    }
    private static void clearScreen(){
        System.out.print("\003\143");
    }
}



